import res_city
import product_template
# import res_country
import res_partner
import res_township
import product_pricelist
import credit_application
import weekly_noti
import product_reorder
import stock_transfer_details
import app_version
import push_noti_app
import stock
import res_branch
import push_image_app
import app_announcement
import noti_by_customer
