from openerp.osv import fields, osv
import time
import datetime

class credit_application(osv.osv):
    _name = 'credit.application'
    _columns = {
                    'name': fields.char('Company Registration Number', required=True),
                    'date_of_application': fields.date('Date of Application'),                    
                    'sole_proprietor': fields.boolean('Sole Proprietor', default=False),
                    'corporation': fields.boolean('Corporation', default=False),
                    'others': fields.boolean('Others', default=False),
                    'date_received': fields.date('Date Received'),                    
                    'registration_date': fields.date('Registration Date'), 
                    'number_of_employees': fields.integer('Number of Employees'),
                    'company_register_name': fields.char('Company Register Name'),
                    'trade_brand_name': fields.char('Trade Name/Brand Name'),
                    'company_street': fields.char('Street'),
                    'company_street2': fields.char('Street2'),      
                    'company_city_id': fields.many2one('res.city', 'City'),
                    'company_state_id': fields.many2one("res.country.state", 'State'),
                    'company_country_id': fields.many2one('res.country', 'Country'),       
                    'company_township_id':fields.many2one('res.township','Township'),
                    'company_zip': fields.char('Zip', size=24),
                    'company_phone': fields.char('Phone'), 
                    'residence_street': fields.char('Street'),
                    'residence_street2': fields.char('Street2'),      
                    'residence_city_id': fields.many2one('res.city', 'City'),
                    'residence_state_id': fields.many2one("res.country.state", 'State'),
                    'residence_country_id': fields.many2one('res.country', 'Country'),       
                    'residence_township_id':fields.many2one('res.township','Township'),
                    'residence_zip': fields.char('Zip', size=24),
                    'residence_phone': fields.char('Phone'),
                    'company_nrc': fields.char("Customer's NRC(For Individual/Sole Propprietor)"), 
                    'customer_email': fields.char('Customer Email Address'),
                    'phone': fields.char('Phone'),
                    'mobile': fields.char('Mobile'),
                    'business_phone': fields.boolean('Business', default=False),
                    'residential_phone': fields.boolean('Residential', default=False),
                    'viber': fields.boolean('Viber', default=False),
                    'wechat': fields.boolean('Wechat', default=False),
                    'whatsapp': fields.boolean('WhatsApp', default=False),
                    'owner': fields.char('Owner/Managing Director'),
                    'owner_email': fields.char('E-mail Address'),
                    'owner_phone': fields.char('Telephone Number'),
                    'owner_mobile': fields.char('Mobile Phone'),
                    'purchasing_manager': fields.char('Purchasing Manager/In-Charge'),
                    'pm_email': fields.char('E-mail Address'),
                    'pm_phone': fields.char('Telephone Number'),
                    'pm_mobile': fields.char('Mobile Phone'),
                    'operation_manager': fields.char('Operations Manager/In-Charge'),
                    'om_email': fields.char('E-mail Address'),
                    'om_phone': fields.char('Telephone Number'),
                    'om_mobile': fields.char('Mobile Phone'),
                    'finance_manager': fields.char('Finance Manager/In-Charge'),
                    'fm_email': fields.char('E-mail Address'),
                    'fm_phone': fields.char('Telephone Number'),
                    'fm_mobile': fields.char('Mobile Phone'),
                    'cash': fields.boolean('Cash', default=False),
                    'bank': fields.boolean('Bank Deposit/Transfer', default=False),
                    'company_cheque': fields.boolean('Company Cheque', default=False),
                    'other_specify': fields.char('Other(Specify)'),
                    'date_of_opening': fields.date('Date of Account Opening/Number of Years Banking'),
                    'bank_name': fields.char('Bank Name'),
                    'bank_register_street': fields.char('Street'),
                    'bank_register_street2': fields.char('Street2'),      
                    'bank_register_city_id': fields.many2one('res.city', 'City'),
                    'bank_register_state_id': fields.many2one("res.country.state", 'State'),
                    'bank_register_country_id': fields.many2one('res.country', 'Country'),       
                    'bank_register_township_id':fields.many2one('res.township','Township'),'bank_register_street': fields.char('Street'),
                    'bank_register_zip': fields.char('Zip', size=24),
                    'bank_officer': fields.char('Bank Officer/Manager'),
                    'bank_officer_email': fields.char('Email Address'),
                    'bank_officer_phone': fields.char('Telephone Number'),
                    'bank_officer_mobile': fields.char('Mobile Phone'),
                }